export const fakeBuyerDetails = [
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Randi Leonard",
    companyName: "HOPELI",
    email: "randileonard@hopeli.com",
    telephoneFax: "+23 (974) 401-2323",
    companyAddress: "212 Prescott Place, Jardine, Virginia, 5081",
    nationality: "Brazil",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Mrs",
    representedBy: "Foster Wilkins",
    companyName: "AQUASURE",
    email: "fosterwilkins@aquasure.com",
    telephoneFax: "+23 (825) 537-3107",
    companyAddress: "854 Bristol Street, Urbana, District Of Columbia, 8177",
    nationality: "Brazil",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Pennington Berger",
    companyName: "ENAUT",
    email: "penningtonberger@enaut.com",
    telephoneFax: "+23 (946) 491-3013",
    companyAddress: "777 Franklin Avenue, Omar, Guam, 4200",
    nationality: "Jamaica",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Dr",
    representedBy: "Aurelia Le",
    companyName: "EXTRAGENE",
    email: "aureliale@extragene.com",
    telephoneFax: "+23 (933) 508-2135",
    companyAddress: "906 Front Street, Greenbush, Pennsylvania, 705",
    nationality: "Italian",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Dr",
    representedBy: "Lynette Hill",
    companyName: "TERSANKI",
    email: "lynettehill@tersanki.com",
    telephoneFax: "+23 (882) 436-2623",
    companyAddress: "276 Nassau Avenue, Devon, Nevada, 5465",
    nationality: "Italian",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Dr",
    representedBy: "Lisa Ballard",
    companyName: "PORTICA",
    email: "lisaballard@portica.com",
    telephoneFax: "+23 (921) 448-2559",
    companyAddress: "880 Clark Street, Oasis, New Mexico, 331",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Moore Abbott",
    companyName: "CINESANCT",
    email: "mooreabbott@cinesanct.com",
    telephoneFax: "+23 (870) 448-3892",
    companyAddress: "247 Harbor Lane, Frank, Montana, 3112",
    nationality: "Italian",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Mrs",
    representedBy: "Robin Hurley",
    companyName: "KIOSK",
    email: "robinhurley@kiosk.com",
    telephoneFax: "+23 (969) 544-2381",
    companyAddress: "124 Cherry Street, Bedias, Virgin Islands, 3271",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Mrs",
    representedBy: "Celina Hudson",
    companyName: "SNACKTION",
    email: "celinahudson@snacktion.com",
    telephoneFax: "+23 (854) 543-2632",
    companyAddress: "215 Elliott Place, Waterloo, Marshall Islands, 6174",
    nationality: "Brazil",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Dr",
    representedBy: "Jefferson Buchanan",
    companyName: "QUANTALIA",
    email: "jeffersonbuchanan@quantalia.com",
    telephoneFax: "+23 (830) 452-3881",
    companyAddress: "200 Engert Avenue, Gibbsville, Massachusetts, 8182",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: false,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Kristina Bentley",
    companyName: "OPTICOM",
    email: "kristinabentley@opticom.com",
    telephoneFax: "+23 (923) 491-3338",
    companyAddress: "283 Lois Avenue, Morningside, Kansas, 8196",
    nationality: "Jamaica",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Carla Petty",
    companyName: "HYPLEX",
    email: "carlapetty@hyplex.com",
    telephoneFax: "+23 (974) 451-3207",
    companyAddress: "397 Schenck Court, Nutrioso, Maine, 9709",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Dr",
    representedBy: "Blackwell Frye",
    companyName: "ENOMEN",
    email: "blackwellfrye@enomen.com",
    telephoneFax: "+23 (866) 506-3762",
    companyAddress:
      "867 Hunterfly Place, Cavalero, Federated States Of Micronesia, 1094",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
  {
    activated: true,
    website: "https://stacopoc@stacoinc.com",
    title: "Mr",
    representedBy: "Moran Stanton",
    companyName: "ILLUMITY",
    email: "moranstanton@illumity.com",
    telephoneFax: "+23 (877) 528-2476",
    companyAddress: "796 Knight Court, Wanship, Maryland, 4544",
    nationality: "Mexico",
    companyRegistrationNumber: "RC77383",
  },
];

export const tableHeaders = [
  "Company Name",
  "Company Reg No",
  "Rep By",
  "Title",
  "Nationality",
  "Telephone Fax",
  "Email",
  "Website",
  "Status",
  "Edit",
  "Delete",
];

export const userKey = "userDetails";
